### ISSUE TITLE
Remove reactive extensions

### ISSUE THREAD

**Issue by swoolcock** [swoolcock/AvaloniaTAS#21]
To make this project easier to manage, I'm thinking about whether we should just rip out all the reactive extensions and use basic Avalonia commands etc. instead.

When I started this project, reactive was all the rage and one of the recommended templates for Avalonia projects.  I think it's honestly more verbose and confusing than it's worth.

I think removing it will actually be less effort than it sounds and will make maintenance a lot simpler down the track.  It's also a lot less scary for people who want to contribute to the project.

@psyGamer thoughts?

**Comment by psyGamer** [comment]
I'm not really sure how exactly everything would change, but if you think it would make it more maintainable, go for it!

**Comment by swoolcock** [comment]
Effort to remove this given how much the Avalonia team push it.
