### ISSUE TITLE
Question about the DMG installer background

### ISSUE THREAD

**Issue by jakobhellermann** [swoolcock/AvaloniaTAS#22]
Did you make the DMG install background https://github.com/swoolcock/AvaloniaTAS/blob/main/deployment/dmg_background.png?

Can I use it in my own tool? https://github.com/jakobhellermann/Atlas

**Comment by swoolcock** [comment]
I did make it, yes.  Uh.... as long as there's no confusion over which tool is which there shouldn't be a problem.  AvaloniaTAS doesn't even have an AppIcon yet, so as long as yours has its own it should be pretty clear.
